import numpy as np
from typing import Dict, Any, Tuple

class HydrogelMonteCarloEngine:
    """
    Mathematical physics engine focused on Level 3: Statistical Variance.
    Executes high-speed Monte Carlo simulations to model laboratory sensor noise.
    """
    def __init__(self, lcst_celsius: float = 32.0, scaling_constant_k: float = 150.0):
        """
        Initializes the stochastic engine with core baseline parameters.
        """
        self.lcst = lcst_celsius
        self.k_factor = scaling_constant_k

    def run_monte_carlo_simulation(
        self, 
        nominal_inputs: Dict[str, float], 
        error_bounds: Dict[str, float], 
        samples: int = 10000
    ) -> Dict[str, Any]:
        """
        Generates Gaussian noise distributions over input parameters and computes 
        the cumulative probability distribution for physical hydrogel metrics.
        
        Args:
            nominal_inputs (Dict): Standard operational setpoints from the lab.
            error_bounds (Dict): Standard deviations representing equipment noise.
            samples (int): Total number of stochastic iterations to execute.
        """
        # 1. Generate Gaussian distributions for input telemetry with safety clipping
        # Clipping avoids unphysical negative values generated by extreme tail noise
        voltages = np.random.normal(nominal_inputs["voltage_kv"], error_bounds["voltage_kv"], samples)
        voltages = np.maximum(voltages, 1.0)
        
        viscosities = np.random.normal(nominal_inputs["viscosity_pa_s"], error_bounds["viscosity_pa_s"], samples)
        viscosities = np.maximum(viscosities, 0.01)
        
        flows = np.random.normal(nominal_inputs["flow_rate_ml_h"], error_bounds["flow_rate_ml_h"], samples)
        flows = np.maximum(flows, 0.01)
        
        temperatures = np.random.normal(nominal_inputs["temperature_celsius"], error_bounds["temperature_celsius"], samples)

        # 2. Level 4 Math: Vectorized Electrospinning Nanofiber Diameter Calculation
        operational_ratio = (flows * viscosities) / voltages
        fiber_diameters = self.k_factor * np.sqrt(operational_ratio)

        # 3. Level 1 Math: Vectorized Sigmoidal Thermal Swelling Calculation
        max_swelling = 3.5
        min_swelling = 1.0
        thermal_deviation = 0.5 * (temperatures - self.lcst)
        swelling_ratios = min_swelling + (max_swelling - min_swelling) / (1.0 + np.exp(thermal_deviation))

        # 4. Statistical Analysis Pipeline: Extract mean, std, and 95% confidence intervals
        return {
            "simulation_metadata": {
                "total_samples_computed": samples,
                "confidence_interval_pct": 95.0
            },
            "fiber_diameter_stats_nm": {
                "mean": float(np.mean(fiber_diameters)),
                "std_dev": float(np.std(fiber_diameters)),
                "p_low_2_5": float(np.percentile(fiber_diameters, 2.5)),
                "p_high_97_5": float(np.percentile(fiber_diameters, 97.5))
            },
            "swelling_ratio_stats_dimensionless": {
                "mean": float(np.mean(swelling_ratios)),
                "std_dev": float(np.std(swelling_ratios)),
                "p_low_2_5": float(np.percentile(swelling_ratios, 2.5)),
                "p_high_97_5": float(np.percentile(swelling_ratios, 97.5))
            },
            "raw_stochastic_distribution": {
                "fiber_diameter_nm": fiber_diameters.tolist(),
                "swelling_ratio": swelling_ratios.tolist()
            }
        }


# =====================================================================
# STANDALONE STOCHASTIC RUNTIME VERIFICATION (SANITY CHECK)
# =====================================================================
if __name__ == "__main__":
    print("Launching Monte Carlo matrix verification simulation wrapper...")
    stochastic_engine = HydrogelMonteCarloEngine()
    
    # Lab technician nominal targets
    target_setpoints = {
        "voltage_kv": 20.0,
        "viscosity_pa_s": 1.3,
        "flow_rate_ml_h": 0.5,
        "temperature_celsius": 31.5  # Positioned right at the LCST transition window
    }
    
    # Realistic sensor standard deviations observed in experimental runs
    sensor_variance = {
        "voltage_kv": 0.5,          # +/- 0.5 kV power supply oscillation
        "viscosity_pa_s": 0.05,      # Solution batch heterogeneity error
        "flow_rate_ml_h": 0.02,      # Syringe pump micro-stepper friction noise
        "temperature_celsius": 0.8   # Environmental thermal room control fluctuation
    }
    
    # Execute high-speed simulation with 10,000 randomized parallel evaluations
    results = stochastic_engine.run_monte_carlo_simulation(
        nominal_inputs=target_setpoints,
        error_bounds=sensor_variance,
        samples=10000
    )
    
    print("\n📊 [STOCHASTIC DISTRIBUTION MATRIX COMPLETED]:")
    print(f"   ➤ Fiber Diameter: {results['fiber_diameter_stats_nm']['mean']:.2f} +/- {results['fiber_diameter_stats_nm']['std_dev']:.2f} nm")
    print(f"   ➤ 95% Space Range: [{results['fiber_diameter_stats_nm']['p_low_2_5']:.2f} nm TO {results['fiber_diameter_stats_nm']['p_high_97_5']:.2f} nm]")
    print(f"   ➤ Hydrogel Swelling Swelling Mean: {results['swelling_ratio_stats_dimensionless']['mean']:.4f}")
    print(f"   ➤ 95% Swelling Range: [{results['swelling_ratio_stats_dimensionless']['p_low_2_5']:.4f} TO {results['swelling_ratio_stats_dimensionless']['p_high_97_5']:.4f}]")