from typing import Any, Dict, Tuple
import numpy as np


class HydrogelMonteCarloEngine:
    """Mathematical physics engine focused on Level 3: Statistical Variance.

    Executes high-speed Monte Carlo simulations to model laboratory sensor noise,
    predicting structural and thermodynamic uncertainties via vectorised
    NumPy operations.
    """

    def __init__(
        self, lcst_celsius: float = 32.0, scaling_constant_k: float = 150.0
    ):
        """Initializes the stochastic engine with core baseline parameters.

        Args:
            lcst_celsius (float, optional): Lower Critical Solution Temperature
                (LCST) boundary in Celsius. Defaults to 32.0.
            scaling_constant_k (float, optional): Empirical proportionality
                coefficient for electrospinning fiber scales. Defaults to 150.0.
        """
        self.lcst = lcst_celsius
        self.k_factor = scaling_constant_k

    def run_monte_carlo_simulation(
        self,
        nominal_inputs: Dict[str, float],
        error_bounds: Dict[str, float],
        samples: int = 10000,
    ) -> Dict[str, Any]:
        """Generates Gaussian noise distributions over input parameters to run stochastic analysis.

        This method projects standard laboratory errors through non-linear multi-scale
        hydrogel equations. The simulation propagates standard deviation variances:
        $$x_{\\text{stochastic}} \\sim \\mathcal{N}(\\mu_{\\text{nominal}}, \\sigma_{\\text{variance}})$$

        Because the underlying physical models (scaling laws and sigmoidal phase
        transitions) are highly non-linear, symmetric input noise results in skewed,
        non-Gaussian response distributions. Cumulative probability bounds are
        extracted using empirical percentiles:
        $$\\text{Confidence Interval (95\\%)} = [P_{2.5}, P_{97.5}]$$

        Args:
            nominal_inputs (Dict[str, float]): Expected targets set by the operator.
                Must include keys: "voltage_kv", "viscosity_pa_s", "flow_rate_ml_h",
                and "temperature_celsius".
            error_bounds (Dict[str, float]): Sensor noise standard deviations.
                Must match keys in nominal_inputs. Values should be non-negative.
            samples (int, optional): Total count of randomized parallel iterations
                to execute. Must be strictly greater than zero. Defaults to 10000.

        Returns:
            Dict[str, Any]: Dictionary containing processed statistics and raw data distribution:
                - "simulation_metadata": Sample size and configuration details.
                - "fiber_diameter_stats_nm": Mean, std deviation, and 95% CI for diameters.
                - "swelling_ratio_stats_dimensionless": Shifted phase stats due to non-linearity.
                - "raw_stochastic_distribution": Complete list profiles for custom plotting arrays.

        Raises:
            ValueError: If samples <= 0 or if any required dictionary key is missing or invalid.
        """
        # Validate sample count integrity
        if samples <= 0:
            raise ValueError(
                f"Simulation samples must be a positive integer. Received: {samples}"
            )

        # Validate dictionary input structure
        required_keys = {
            "voltage_kv",
            "viscosity_pa_s",
            "flow_rate_ml_h",
            "temperature_celsius",
        }
        if not required_keys.issubset(
            nominal_inputs.keys()
        ) or not required_keys.issubset(error_bounds.keys()):
            raise ValueError(
                f"Input dictionaries must contain all required keys: {required_keys}"
            )

        # 1. Generate Gaussian distributions for input telemetry with safety clipping
        # Clipping avoids unphysical negative values generated by extreme tail noise
        voltages = np.random.normal(
            nominal_inputs["voltage_kv"], error_bounds["voltage_kv"], samples
        )
        voltages = np.maximum(voltages, 1.0)  # Avoid division by zero/negative fields

        viscosities = np.random.normal(
            nominal_inputs["viscosity_pa_s"],
            error_bounds["viscosity_pa_s"],
            samples,
        )
        viscosities = np.maximum(viscosities, 0.01)  # Fluid must possess viscosity

        flows = np.random.normal(
            nominal_inputs["flow_rate_ml_h"],
            error_bounds["flow_rate_ml_h"],
            samples,
        )
        flows = np.maximum(flows, 0.01)  # Avoid negative feeding mass rates

        temperatures = np.random.normal(
            nominal_inputs["temperature_celsius"],
            error_bounds["temperature_celsius"],
            samples,
        )

        # Vectorized Electrospinning Nanofiber Diameter Calculation
        # d = k * sqrt((Q * eta) / V)
        operational_ratio = (flows * viscosities) / voltages
        fiber_diameters = self.k_factor * np.sqrt(operational_ratio)

        # Vectorized Sigmoidal Thermal Swelling Calculation
        max_swelling = 3.5
        min_swelling = 1.0
        thermal_deviation = 0.5 * (temperatures - self.lcst)

        # Safe array clipping to avoid floating-point overflow during np.exp calculation
        thermal_deviation = np.clip(thermal_deviation, -700.0, 700.0)
        swelling_ratios = min_swelling + (max_swelling - min_swelling) / (
            1.0 + np.exp(thermal_deviation)
        )

        # 4. Statistical Analysis Pipeline: Extract mean, std, and 95% confidence intervals
        return {
            "simulation_metadata": {
                "total_samples_computed": samples,
                "confidence_interval_pct": 95.0,
            },
            "fiber_diameter_stats_nm": {
                "mean": float(np.mean(fiber_diameters)),
                "std_dev": float(np.std(fiber_diameters)),
                "p_low_2_5": float(np.percentile(fiber_diameters, 2.5)),
                "p_high_97_5": float(np.percentile(fiber_diameters, 97.5)),
            },
            "swelling_ratio_stats_dimensionless": {
                "mean": float(np.mean(swelling_ratios)),
                "std_dev": float(np.std(swelling_ratios)),
                "p_low_2_5": float(np.percentile(swelling_ratios, 2.5)),
                "p_high_97_5": float(np.percentile(swelling_ratios, 97.5)),
            },
            "raw_stochastic_distribution": {
                "fiber_diameter_nm": fiber_diameters.tolist(),
                "swelling_ratio": swelling_ratios.tolist(),
            },
        }


# =====================================================================
# STANDALONE STOCHASTIC RUNTIME VERIFICATION (SANITY CHECK)
# =====================================================================
if __name__ == "__main__":
    print("Launching Monte Carlo matrix verification simulation wrapper...")
    stochastic_engine = HydrogelMonteCarloEngine()

    # Lab technician nominal targets
    target_setpoints = {
        "voltage_kv": 20.0,
        "viscosity_pa_s": 1.3,
        "flow_rate_ml_h": 0.5,
        "temperature_celsius": 31.5,  # Positioned right at the LCST transition window
    }

    # Realistic sensor standard deviations observed in experimental runs
    sensor_variance = {
        "voltage_kv": 0.5,  # +/- 0.5 kV power supply oscillation
        "viscosity_pa_s": 0.05,  # Solution batch heterogeneity error
        "flow_rate_ml_h": 0.02,  # Syringe pump micro-stepper friction noise
        "temperature_celsius": 0.8,  # Environmental thermal room control fluctuation
    }

    try:
        # Execute high-speed simulation with 10,000 randomized parallel evaluations
        results = stochastic_engine.run_monte_carlo_simulation(
            nominal_inputs=target_setpoints,
            error_bounds=sensor_variance,
            samples=10000,
        )

        print("\n📊 [STOCHASTIC DISTRIBUTION MATRIX COMPLETED]:")
        print(
            f"   ➤ Fiber Diameter: {results['fiber_diameter_stats_nm']['mean']:.2f} "
            f"+/- {results['fiber_diameter_stats_nm']['std_dev']:.2f} nm"
        )
        print(
            f"   ➤ 95% Space Range: [{results['fiber_diameter_stats_nm']['p_low_2_5']:.2f} nm "
            f"TO {results['fiber_diameter_stats_nm']['p_high_97_5']:.2f} nm]"
        )
        print(
            f"   ➤ Hydrogel Swelling Mean: {results['swelling_ratio_stats_dimensionless']['mean']:.4f}"
        )
        print(
            f"   ➤ 95% Swelling Range: [{results['swelling_ratio_stats_dimensionless']['p_low_2_5']:.4f} "
            f"TO {results['swelling_ratio_stats_dimensionless']['p_high_97_5']:.4f}]"
        )

    except ValueError as err:
        print(f"❌ Simulation execution aborted due to constraint error: {err}")